apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-logger
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/JessicaApBueno/descomplicando-gitops-no-kubernetes-argocd"
    targetRevision: feat/day2
    path: random-logger/helm
    helm: {}
  destination:
    namespace: random-logger
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
